### ISSUE TITLE
Can not parse [A-C], [A:C]

### ISSUE THREAD

**Issue by volanja** [udondan/hostlist_expression-ruby#1]
I tried your gem for implement to `ansible_spec`, but I can't parse [A-C], [A:C].
Could you check this case?

``` Example
$ gem install hostlist_expression
Fetching: hostlist_expression-0.2.0.gem (100%)
Successfully installed hostlist_expression-0.2.0
Parsing documentation for hostlist_expression-0.2.0
Installing ri documentation for hostlist_expression-0.2.0
1 gem installed

$ pry
[1] pry(main)> require 'hostlist_expression'
=> true
[2] pry(main)> hosts = hostlist_expression("host-[1-3].com")
=> ["host-1.com", "host-2.com", "host-3.com"]
[3] pry(main)> hosts = hostlist_expression("host-[1:3].com")
=> ["host-1.com", "host-2.com", "host-3.com"]
[4] pry(main)> hosts = hostlist_expression("host-[A-C].com")
=> []
[5] pry(main)> hosts = hostlist_expression("host-[A:C].com")
=> []
```

**Comment by udondan** [comment]
Thanks @volanja! The problem was caused by a small feature I implemented quickly before release, reverse ranges (e.g. `host[20-10].com`) which I only tested with numeric ranges... That shows how important tests are... I added a few more with sequences and mixed patterns.

**Comment by volanja** [comment]
Thank you to early resolve.
If you are interested in automated test, I think that it may be automated by Travis-CI.
I'll try create script for Travis. And then add pull request.
